### ISSUE TITLE
Twitter Video Nice Rendering Glitch

### ISSUE THREAD

**Issue by philmaas** [nvrmind/IssueTracker#12]
There is an interesting issue with the twitter feature going on. Videos appear very glitchy at least for me:

https://twitter.com/twitter/statuses/952233585943220225

BTW: The issue reported in the forums about not being able to enter the twitter authorization code seems to be fixed and i could renew the authorization and post to twitter.

**Comment by philmaas** [comment]
another comment on the previously reported AMD issue (crash on saving a scene with strokes) seems to be resolved in the latest version, thanks! 
I guess no need to open and close an issue for that, but wanted to let you know.

**Comment by daseyb** [comment]
Thanks for letting us know about the AMD thing, I'm glad to hear that!

I'll look into the Twitter video thing over the next few days and we'll probably upload a hotfix next week :)

**Comment by daseyb** [comment]
We pushed a small hot fix that fixes this
