### ISSUE TITLE
Can not find controllers

### ISSUE THREAD

**Issue by ZebraSnow** [nvrmind/IssueTracker#13]
I use HTC VIVE.
Before 8.13beta, I can use ANIMVR. But after updating, I can not find my controllers when I open ANIMVR. So I can not use it. Please help.

**Comment by daseyb** [comment]
Hi, can you make sure that both controllers are on and tracking before you start AnimVR and test again?
If it still doesn’t work I recommend reinstalling AnimVR through Steam.
Sorry for the inconvenience, hope that works!

From: ZebraSnow
Sent: Wednesday, 17 January 2018 15:59
To: nvrmind/IssueTracker
Cc: Subscribed
Subject: [nvrmind/IssueTracker] Can not find controllers (#13)

I use HTC VIVE.
Before 8.13beta, I can use ANIMVR. But after updating, I can not find my controllers when I open ANIMVR. So I can not use it. Please help.

**Comment by ZebraSnow** [comment]
Hi. My actural controllers are proper woking on other apps.
I reinstalled ANIMVR from steam. But still can not find the controllers when I using ANIMVR. When I opened ANIMAVR, controllers just dissapeared.
Here is a video I captured, which shows the issue.
https://youtu.be/RS5Dc5NL_84

**Comment by daseyb** [comment]
Thanks for the video! This is a weird issue, I haven't run into that so far. The only thing I can think of that might be causing that is that we recently updated the SteamVR Unity plugin.
Do you have the latest version of SteamVR installed?
In any case, I'll investigate!

**Comment by ZebraSnow** [comment]
Hi! Good News!
I checked the steamVR version, it was version 1511294946. I thought it was not the latest version and I did not know why it did not automaticly update when I set it into automaticly update. 
Then I reinstalled it. Now it is version 1515522829. And it is working for ANIMVR! Finally! Yes!!! Thanks!!! And sorry to bother you.
ANIMVR is amazing!!!
But here I want to give an advice. I want to suck the color!!! Everytime I change the color I can never change it back. Hope a color sucker tool will help! (Or maybe it has, I just did not see it?)

**Comment by daseyb** [comment]
Glad it's working! Thanks for figuring that out, if anyone else has that
issue we can direct them to your solution :)

You can pick colors by pressing the bottom of your right touchpad (it has a
little pipette icon on it).

When you get close to a line while holding that button you'll get the color
of that line
