### ISSUE TITLE
Mirror tool mirrors all frames in a layer, doesn't work on selections of strokes

### ISSUE THREAD

**Issue by StainyGrimes** [nvrmind/IssueTracker#14]
When using the mirror tool it mirrors the contents of all of the individual frames in the active layer.

**Comment by daseyb** [comment]
Both of these things should work, but I found a bug that's preventing that.
Once the bug is fixed mirroring single frames is enabled by switching to "frame mode" in the transform menu.

**Comment by daseyb** [comment]
Fixed in Beta 8.16
