### ISSUE TITLE
Onion skin default opacity is set too high

### ISSUE THREAD

**Issue by StainyGrimes** [nvrmind/IssueTracker#16]
The opacity of onion skins, by default, is higher than the sliders can actually go. If you adjust the sliders the opacity becomes normal again.

Even the left- and right-most onion skins are visible, even though those settings appear to default to 0% opacity.

**Comment by daseyb** [comment]
Thanks for letting us know, that should be an easy adjustment :)

**Comment by daseyb** [comment]
Fixed in Beta 8.16
