### ISSUE TITLE
left-right orientation for controllers

### ISSUE THREAD

**Issue by zolvladir** [nvrmind/IssueTracker#17]
At some point, the controllers changed from left to right. Oculus rift. I'm right handed and the left hand does not know how. Are there any options for selecting the orientation of the controllers? 

With best regards!

**Comment by daseyb** [comment]
Hi :)
You can hold the bottom part of the controllers together to switch between
right handed and left handed mode.
Cheers, Dario

**Comment by daseyb** [comment]
We have made this a menu option, so it shouldn't happen accidentally any more!
