### ISSUE TITLE
feature request - other tools obey selection

### ISSUE THREAD

**Issue by df-0** [nvrmind/IssueTracker#27]
would be useful if (like in photoshop/sketchbook) the erase/recolour/mirror tools were restricted to the selection area, so you could highlight a region and recolour it without worrying about messing other stuff up. Of course you then run into the problem of when users select something and forget they selected it and none of the tools work, photoshop has the same issue - but as long as there's clear visual feedback on selection mode that miiight be ok?

**Comment by daseyb** [comment]
Recolor and nudge should already do that and I fixed a bug in the mirror tool, so that should work in the next release.

I'll also add it to the eraser :)

**Comment by daseyb** [comment]
Fixed in Beta 8.16

**Comment by df-0** [comment]
😎
