### ISSUE TITLE
Alembic don´t export the same number of sides of sphere brush

### ISSUE THREAD

**Issue by DanielMartinezLara** [nvrmind/IssueTracker#4]
Hi!
Alembic seems that don´t export the same number of sides of sphere brush In to Blender or Maya.
In AnimVR is 8 and after import is only 5
![2captura](https://user-images.githubusercontent.com/35196303/34657395-e4aa6440-f425-11e7-8b5a-11bfdb7c7686.PNG)

**Comment by daseyb** [comment]
Oh, I should update that in the CPU mesh generation code, thanks for letting me know it’s an issue!

**Comment by DanielMartinezLara** [comment]
Perfect!
