### ISSUE TITLE
25 fps settings

### ISSUE THREAD

**Issue by Luaisa** [nvrmind/IssueTracker#44]
It would be very important to have the opportunity to set the stage setting at 25 fps.

**Comment by daseyb** [comment]
Ok, that's an easy addition, thanks for letting us know it's important to
you!

**Comment by Luaisa** [comment]
Awesome, thanks a lot!

**Comment by animoka** [comment]
Sorry, do you have any estimate data for your next release? It would be very important for us to try this feature as soon as possible.

**Comment by daseyb** [comment]
I think we should be able to push an update this weekend :)

**Comment by animoka** [comment]
Cool, thank you and good job, guys!

**Comment by animoka** [comment]
Hi guys, any news about when you will publish the next release? All the new features and bugs fix would save a lot of time in our daily use of AnimVR.
