### ISSUE TITLE
General settings.

### ISSUE THREAD

**Issue by Luaisa** [nvrmind/IssueTracker#49]
It would save time to have the opportunity to save some generic stage settings in order to avoid redoing it everytime we start a new scene. 

For example the "generic settings" could include:
- fps settings.
- background color.
- in\out timeline.
- left or right hand.

**Comment by daseyb** [comment]
Left or right hand should already be saved and restored when you open up
AnimVR again. Is that not the case? (If it doesn't work it's definitely a
bug).
The other ones totally make sense and should be easy to add!

**Comment by df-0** [comment]
Yup, I was going to request this for brush smoothness actually

**Comment by df-0** [comment]
oooh, and Ambient Occlusion!
