### ISSUE TITLE
Hands swapping on Rift for left-handed people

### ISSUE THREAD

**Issue by diegocortassa** [nvrmind/IssueTracker#5]
Hi,
we are testing AnimVR but we miss an important feature. As Oculus rift controllers are asymmetrical we need a way to swap controllers as it is impossible for a left-handed to draw.
Do you have any solution?
Thanks!

**Comment by daseyb** [comment]
We are working on this right now and you can expect that update to go live
in the next two weeks.
Sorry for the inconvenience!

**Comment by diegocortassa** [comment]
This is great news!
Many thanks!
