### ISSUE TITLE
Folder structure in the Import, Export and Save files management.

### ISSUE THREAD

**Issue by animoka** [nvrmind/IssueTracker#50]
In order to manage a huge amount of data it would very useful to have the opportunity to see & select a folder in the import, export and save brunches,

**Comment by daseyb** [comment]
Yes, Milan has been getting annoyed with that as well and we are actually
planning on redesigning the import menu to accommodate larger projects and
more import types.
We hope that'll go in one of the next updates!

**Comment by df-0** [comment]
👍 agree!
