### ISSUE TITLE
Alembic curves export option instead of meshes for a smaller .abc file.

### ISSUE THREAD

**Issue by animoka** [nvrmind/IssueTracker#52]
Could be interesting adding an option in the alembic export so that the user can choose the best file settings to export the animation: meshes, with more 3D details but large files, or curves, with less details but with a smaller file size.

**Comment by daseyb** [comment]
Since the last small update (last night) we are exporting curves in
addition to meshes. I'll look into adding some options to the export so you
can decide which one you want.

**Comment by df-0** [comment]
mentioned this on the slack, but yeah would be great if we had the option to export both mesh and curves in the same file, so I didn't have to do stuff like this :-)
![image](https://user-images.githubusercontent.com/16046786/39675201-6aae0656-514f-11e8-9e2a-9bc1ed776765.png)
