### ISSUE TITLE
bug: in out-range gets set wrong when you import an obj

### ISSUE THREAD

**Issue by df-0** [nvrmind/IssueTracker#61]
1) create a new scene
2) import an obj
3) switch back to the default paint layer
4) paint a frame
5) click the 'new frame' trigger
6) paint another frame
7) step back a frame
8) try stepping forward again - you _can't_! for some reason the frame range is set to 1-1, even though your current layer has 2 frames. 

This doesn't seem to occur if you skip the 'import an obj' step, don't *think* there's anything weird about my obj tho, it's just a grid! Just double checked it, seems reasonable, it is rather a huge grid tho, probably shoulda turned down the subdivisions but hey, it loads, so I don't mind :-)

Haven't tested it with another OBJ, would be surprised if it's caused by that specific OBJ but lemme know if you want me to test it further...

```
# File exported by Houdini 15.5.480 (www.sidefx.com)
# 112800 points
# 459200 vertices
# 132800 primitives
# Bounds: [-10.0179996, -0.0179999992, -10.0179996] to [10.0179996, 0.0179999992, 10.0179996]
g 
v -10 0.0179999992 -10
v -10 0.0167880747 -9.99350643
v -9.99382496 0.0167880747 -9.99799347... etc
```

**Comment by daseyb** [comment]
This is a side effect of the loop around layer behaviour, since there is another issue describing that, I'll close this one :)
