### ISSUE TITLE
Controller hands have swapped

### ISSUE THREAD

**Issue by 3dbumper** [nvrmind/IssueTracker#62]
Booted up AnimVR on my Vive tonight, and my hands are swapped such that the pencil is in my left hand. I have confirmed that the hands are correct in Steam otherwise. Is there an option somewhere to change this?

**Comment by daseyb** [comment]
You can switch hands by holding the bottom parts of the controllers
together :)

**Comment by 3dbumper** [comment]
Ah! Thank you very much! I must have inadvertently bonked my controllers together.
