### ISSUE TITLE
The camera format (frame aspect ratio) is not stored in the stage file

### ISSUE THREAD

**Issue by DanielMartinezLara** [nvrmind/IssueTracker#7]
Hi!
I noticed if you choose a different camera format, this option it´s not saved in the stage file.
I you close and open again AnimVR, after open the stage file the camera appear with the default camera format.

Daniel

**Comment by daseyb** [comment]
Ah, it actually is, but there was a bug where it wouldn't get loaded properly. Fixed that, thanks for letting us know :)

**Comment by DanielMartinezLara** [comment]
perfect :)
