### ISSUE TITLE
Can't login to Google Poly

### ISSUE THREAD

**Issue by LaddieErvin** [nvrmind/IssueTracker#72]
The first time I tried to login to Google Poly, a message flashed on screen saying that I couldn't do that in VR. I removed my headset and logged into Google Poly in my browser, put the headset back on and everything had worked fine. I worked for a while, closed AnimVR and then returned to it a few minutes later.

Now I can not log into Google Poly inside of AnimVR. I'm logged in in my browser, but AnimVR still says I have to log in. I select the icon to log in and it doesn't let me. It won't repeat the original message saying I can't log in in VR, it just moves  back and forth and does nothing else.

I logged out of Google Poly, restarted AnimVR and it still didn't work.
I rebooted my system, jumped back into AnimVR and it still didn't work. 
I tried various combinations of being logged in, restarting the software, etc. 

Nothing has worked and now I can't get into my models in Google Poly.   

Thanks for taking a look and for working so hard on this fantastic software.

**Comment by daseyb** [comment]
I've been having similar issues lately. I'll look into what's causing that, sorry for the inconvenience!

**Comment by TheWiselyBearded** [comment]
I too am having this issue, I even tried deleting uninstalling the game, deleting the file system, restarting the computer, and reinstalling. I do appreciate you looking into it @daseyb, and I second @LaddieErvin comment, thank you very much for this fantastic software. Great addition to the workflow for VR design.

**Comment by daseyb** [comment]
It seems like it’s a bug in the Poly Toolkit. I implemented a workaround in
the experimental branch and I’ll see if I can find something to make it
work in the main beta too.

**Comment by LaddieErvin** [comment]
Appears to be working in the latest experimental Beta build as of March 4th, 2018.

**Comment by LaddieErvin** [comment]
Thanks!

**Comment by daseyb** [comment]
Fixed in the current version :)
