### ISSUE TITLE
Baking imported FBX to lightbox "goes all weird" with magenta mesh lines everywhere

### ISSUE THREAD

**Issue by df-0** [nvrmind/IssueTracker#73]
See attached screenshot - imported an FBX that was previously exported from Quill (just as a random test), disabled lighting on it, then tried to bake it to a lightbox. Something happened (took a while) and then when it came back it was covered in magenta lines. I actually don't know if it successfully made a lightbox, I don't really know how they work. Undoing surprisingly brought the mesh back to its original state :-)
https://imgur.com/a/iM9Np

**Comment by daseyb** [comment]
Oh.... That button shouldn't be in the build at all. The bake to lightbox
thing isn't implemented yet and we were using that button to run a test
script for something else...
We'll make sure it's disabled in the next build (until the feature that
it's supposed to activate is actually there) :D
