### ISSUE TITLE
Can't play exported stories - Solved

### ISSUE THREAD

**Issue by LaddieErvin** [nvrmind/IssueTracker#76]
When I run the .exe for an exported story, the software launches and presents me with the option to PLAY or QUIT. The problem is, I don't seem to have a way to select either option so there's no way to play the story.  I'm using an Oculus Rift with touch controllers. Pointing at the options doesn't seem to have any effect (there's no visible target lines coming from the controllers - which are tinted red for some reason) and I've tried most, if not all of the keys on the keyboard with no effect.  I also plugged in an Xbox 360 controller and tried it in case the software was set up for that rather than touch controllers but none of the sticks or buttons did anything. I'm running Windows 10 pro.  Thanks for taking a look.

**Comment by LaddieErvin** [comment]
I just discovered that I CAN get the stories to play - with some difficulty. I have to stand far back in my work zone, then launch the story, then I can "TOUCH" the PLAY option with my Touch controller - the PLAY option then begins to flash. I then pull the trigger on the play controller and the Story starts.  This presents a small usability problem as, most of the time, when I launch a story, the PLAY and QUIT options are outside of my work area and actually behind my sensors so my controllers lose tracking before I'm close enough to "touch" them.

It would be much easier if I could either pull the options menu closer, or if I could select the option just by pointing at it.

Thanks again for creating and continuing to improve AnimVR!

**Comment by daseyb** [comment]
We got rid of the menu in the current version :)
