### ISSUE TITLE
Toolkit import broken with current experimental build

### ISSUE THREAD

**Issue by philmaas** [nvrmind/IssueTracker#80]
Hey there,

Unity 2017.3.0f3
latest AnimVR (experimental) 
Toolkit from Github

-> create Stage
-> double click and paint in animVR
-> save
-> import in unity throws this error:

`NullReferenceException: Object reference not set to an instance of an object
AnimData.LoadFromFile (System.String filepath) (at Assets/AnimVR UnityImporter/Utils/AnimData.cs:2830)
ANIMVR.AnimVRImporter.OnImportAsset (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at Assets/AnimVR UnityImporter/Editor/AnimVRImporter.cs:79)
UnityEditor.Experimental.AssetImporters.ScriptedImporter.GenerateAssetData (ImportRequest request) (at C:/buildslave/unity/build/Editor/Mono/AssetPipeline/ScriptedImporter.cs:12`

`Asset import failed, "Assets/MobileTest.stage" > NullReferenceException: Object reference not set to an instance of an object
AnimData.LoadFromFile (System.String filepath) (at Assets/AnimVR UnityImporter/Utils/AnimData.cs:2830)
ANIMVR.AnimVRImporter.OnImportAsset (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at Assets/AnimVR UnityImporter/Editor/AnimVRImporter.cs:79)
UnityEditor.Experimental.AssetImporters.ScriptedImporter.GenerateAssetData (ImportRequest request) (at C:/buildslave/unity/build/Editor/Mono/AssetPipeline/ScriptedImporter.cs:123)`

**Comment by daseyb** [comment]
Fixed back when we officially released the experimental build :)
