### ISSUE TITLE
bug (main build): undo stops working!

### ISSUE THREAD

**Issue by df-0** [nvrmind/IssueTracker#82]
the undo button stopped working for brushstrokes - it was actually still giving tactile feedback when I pressed it, but not removing any brushstrokes. Similarly I could press the undo button in the menu until it became grayed out, but with no effects on the brushstrokes I'd just drawn. Quit-out -and-come-back-in-again fixed it

**Comment by truly-hype** [comment]
I had the same issue. The undo locked on a previous layer no matter how many more layers or drawings i added. When i erased the “locked undo” drawing, i had the exact issue as above. Same to fix the issue also.

**Comment by daseyb** [comment]
This should be fixed in the current release :)
