### ISSUE TITLE
The video and PNG sequence export options don´t take account the camera format

### ISSUE THREAD

**Issue by DanielMartinezLara** [nvrmind/IssueTracker#9]
Hi!
The video and PNG sequence export options don´t take account the camera format selected in camera layer.
The "capture snapshot" option is working ok.

Daniel

**Comment by daseyb** [comment]
I'll fix the PNG sequence export, but it might be tricky to get it working for video export (we're using a third party plugin to render video files and that has some downsides, eventually we want to replace it with our own code).

**Comment by daseyb** [comment]
I can't reproduce the issue with PNG sequence export. Maybe that was fixed as a result of some other change :)

**Comment by DanielMartinezLara** [comment]
good to know  :)

**Comment by daseyb** [comment]
This should be fixed in the current version :)
